Change redeclaration of alias in DeepReset
Before this change, when DeepReset was used with a class, the following
error appeared:
./submodules/ocean/src/ocean/util/DeepReset.d(253): Error: declaration S
is already defined